name: 382,383 jobs.<job_id>.strategy.matrix.include.<index>.....EXCLUDE or bad position of include/exclude

on:
  workflow_dispatch:

jobs:
  test-nested-lists:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - param:
              nested_param:
                EXCLUDE:
                  - [ "value_A", "value_B" ]
                  - [ "value_C", "value_D" ]
          - param2:
              exclude:
                include:
                  exclude: DEEP_EXCLUDE
        
    steps:
      - name: Print nested value
        run: echo "Value is ${{ matrix.param.nested_param.EXCLUDE[1][0] }}"
      - name: Dump matrix JSON
        run: |
          echo "${{ toJson(matrix) }}"
      - name: Deep exlcude
        run: |
          echo "${{ matrix.param2.exclude.include.exclude }}"
