name: Dot Env Test
on:
  workflow_dispatch:
env:
  "dot.in.top.level": "Top Level"

jobs:
  test-env:
    runs-on: ubuntu-latest
    steps:
      - name: Use Dotted Top-Level Env
        env:
          "dot.in.step.level": "Step Level"
        run: |
          echo "Top Level: ${{ env['dot.in.top.level'] }}"
          echo "Step Level: ${{ env['dot.in.step.level'] }}"

