on:  
  workflow_dispatch:
    inputs:
      environment:
        description: 'What environment would you like to deploy?'
        required: true
        default: 'production'
        type: string

env:
  env1q!.&@?][#silly: "silly"

jobs:
  print-env-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment Variable
        run: echo "env1_silly:"
