name: Dot Env Test
on:
  workflow_dispatch:
env:
  "dot.in.top.level": "Top Level"

jobs:
  "test-matrix":
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os.version: [ "ubuntu-18.04", "ubuntu-20.04" ]
    steps:
      - run: echo "::set-output name=output.with.dot::value"



