name: Dot Env Test
on:
  workflow_dispatch:

jobs:
  check-dot-env:
    runs-on: ubuntu-latest
    env:
      "silly.word": "Hello from a dotted variable!"
    steps:
      - name: Echo Dot Var
        run: |
          echo "Value of silly.word: ${{ env['silly.word'] }}"
