on:  
  workflow_dispatch:
    inputs:
      environment:
        description: 'What environment would you like to deploy?'
        required: true
        default: 'production'
        type: string

env:
  "env1.silly": "just a silly varriable"


        
        
      
