name: Dot Env Test
on:
  workflow_dispatch:
env:
  "dot.in.top.level": "Top Level"

permissions:
  contents: read

jobs:
  "test-matrix":
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os.version: [ "ubuntu-18.04", "ubuntu-20.04" ]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - run: echo "::set-output name=output.with.dot::value"



