name: Test Deeply Nested Matrix

on:
  workflow_dispatch:

jobs:
  test-nested-lists:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        param:
          - name: "config_set_1"
            nested_groups:
              - 
                - "value_A"
                - "value_B"
              - - "value_C"
                - "value_D"

    steps:
      - name: "Print nested value"
        # This demonstrates how to access a value from the nested list-of-lists
        run: echo "Value is ${{ matrix.param.nested_groups[0][0] }}"
