name: Test Deeply Nested Matrix

on:
  workflow_dispatch:

  merge_group:
    branches:
      - main
jobs:
  test-nested-lists:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix: {}
    steps:
      - name: "Print nested value"
        run: echo "Value is ${{ matrix.param.nested_groups[1][0]}}"
