name: Test Advanced Matrix Strategies

on:
  workflow_dispatch:

jobs:
  test-nested-lists:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 'param' is the first <matrix_var>
        param:
          # The list below corresponds to the first <index>
          - name: "config_set_1"
            # 'nested_groups' is the second <matrix_var>
            nested_groups:
              # The outer list below corresponds to the second <index>
              - # The inner list below corresponds to the third <index>
                - "value_A"
                - "value_B"
              - - "value_C"
                - "value_D"

    steps:
      - name: "Print nested value"
        # This demonstrates how to access a value from the nested list-of-lists
        run: echo "Value is ${{ matrix.param.nested_groups[0][0] }}"

  test-matrix-exclude:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define the base matrix axes
        os: [ubuntu-latest, windows-latest]
        version: [1.0, 2.0]

        # 'exclude' is a schema keyword
        exclude:
          # This list provides the <index>
          - # This rule will now correctly match and exclude one job
            os: ubuntu-latest
            version: 1.0
            
            # This is an arbitrary key for path analysis. It is NOT used for matching.
            # 'arbitrary_data' is the first <matrix_var>
            arbitrary_data:
              # 'details' is the second <matrix_var>
              details:
                # 'patch' is the third <matrix_var>
                patch: "special-patch-for-ubuntu"
      
    steps:
      - name: "Run on non-excluded configurations"
        run: |
          echo "Running on OS: ${{ matrix.os }} with version: ${{ matrix.version }}"
