name: Manual Trigger Example

# This workflow will be triggered manually
on:
  workflow_dispatch:

jobs:
  run-manual-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a sample script
      run: echo "This workflow was triggered manually"
